apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rook-ceph
  namespace: argocd
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: false
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: cluster_name
                    operator: In
                    values: [media-cluster]
                  - key: environment
                    operator: In
                    values: [prod]    
          - list:
              elements:
                - appName: sonarr
                - appName: radarr
                - appName: sabnzbd
  template:
    metadata:
      name: 'rook-ceph-{{.appName}}'
    spec:
      project: default
      sources:
        - repoURL: '{{.metadata.annotations.workload_repo_url}}'
          path: 'workloads/{{.appName}}'
          targetRevision: '{{.metadata.annotations.workload_repo_revision}}'
          ref: values
      destination:
        namespace: 'media'
        name: '{{.name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true